[[section-runtime-view]]
== Runtime View


[role="arc42help"]
****
.Contents

In this section of the documentation important use cases will be described in order to understand how the system communicates at runtime. This part of the documentation will be in continuous development.

****

=== Changing your current location:

_Alice : Moves -> Radarin : requests a location update -> Alice's pod -> updates the location_

=== Checking someone else's location:

_Bob : Check's Alice location -> Alice's pod : Sends the current location -> Radarin : Displays Alice's current location_

=== Checking for nearby friends:

* _Alice : checks for nearby friends -> Radarin: Checks for all friends that are nearby (if their distance from Alice is less or equal than a given range) -> update map with those locations -> Display notification_

=== Update friend's locations:

* _Radarin: Asks all Alice's friend's (who are in a determined distance) pods for their location -> Display the returned locations_
* Note: This happens automatically. Deppending on the distance of the friend, it will be updated faster or slower.

=== Load saved locations:

* _Radarin: Requests Alice's pod for its saved locations list -> Display the list on the map_

=== Remove a location from the saved locations:

* _Alice : clicks on the "-" button next to the location to remove -> Radarin: Removes the location from the list. -> Removes the location from the map_

=== Add a location to the saved locations:

* _Alice: Writes a location name in the text area -> Clicks on the "+" button -> Radarin: Adds the current location to the list._

=== Save the changes on the saved locations list:
* _Alice: Makes changes to her locations list -> Radarin: asks Alice's pod to override the saved locations list -> Alice's pod: Updates the location's list._

=== Let a friend see where you are:
* _Alice: clicks the "✓" button next to Bob's name in the friends' list -> Radarin: asks Alice's pod to override the read permissions of the file where the last location is stored -> Alice's pod: Updates the permissions._

=== Revoke permissions to a friend to see where you are:
* _Alice: clicks the "✖" button next to Bob's name in the friends' list -> Radarin: asks Alice's pod to override the read permissions of the file where the last location is stored -> Alice's pod: Updates the permissions._