[[section-runtime-view]]
== Runtime View


[role="arc42help"]
****
.Contents

In this section of the documentation important use cases will be described in order to understand how the system communicates at runtime. This part of the documentation will be in continuous development.

****

=== Changing your current location:

_Alice : Moves -> Radarin : requests a location update -> Alice's pod -> updates the location_

=== Checking someone else's location:

_Bob : Check's Alice location -> Radarin : checks if the location for bob is been updated -> Alice's pod_

* If it's been updated:
_Alice's pod : sends the updated information -> Radarin -> updates the location for Alice on Bob's local DB and displays it_

* Else:
_Alice's pod : sends a message telling Radarin that it's information is up to date -> Radarin : Displays Alice's current location_

=== Checking for nearby friends:

* _Alice : checks for nearby friends -> radarin : checks DB for recent locations -> Radarin -> updates map with those locations_
