[[section-design-decisions]]
== Design Decisions

In this section, we document the decions made that affect the application. However, they are not simply listed, they are explained with their context, status and consequences.
Here we have the decisions made:

=== Usage of google maps API

Context:: 

Obviously, for this app we need a map. So at first thought, like everybody nowadays, Google Maps comes up. 

Decision::

After some investigation and some discussion, we decided that we were going to use the Google Maps API despite the fact that the free or demo part is limited. We thought that for a prototype like this application, we get a very useful API without the need of any payment.

(This was added later) In the end, we provide the option of choosing between Google Maps API and Leaflet API.

Status::

Accepted.

Consequences::

The usage of Google Maps API has brought us several useful functions, like Street view and the different map modes. We take for granted that we won't surpass the limit of the free version by now.

=== Usage of built in SOLID friends 

Context:: 

In this app the work with friends is strictly neccesary (if not it would be useless). Furthermore, there are several ways of storing friends and connection between accounts.

Decision::

Initially, we used to store the friends of each user in a file called "friends.ttl". However, we found out that we could easily use the SOLID friends. In your SOLID pod you can add friends and so we get the list of friends and their pod.

Status::

Accepted.

Consequences::

A very user-friendly way to let the users add friends and very accessible from the SOLID pod webpage. Also, we leave a door open to futher improvement and maybe a friend adding interface. The main counterpart of this is that for testing purposes we need to create several pods and is not as easy as changing a file.

=== Usage of a MongoDB central Database

Context:: 

We need to be able to access the last location of every user and show it to their friends. At first glance a central database to store it seemed a good solution and, even if this goes partially against SOLID principles, we thought the last location was a good trade off for the perfomance boost we would get by avoiding asking the PODs every time.

Decision::

Once we started implementing, we realised that accesing a SOLID POD was not at all as time consuming as we thought, so we decided to keep the idea of the central database in the background just in case and follow the path of asking directly each POD. This decision was taken after testing the time a POD request takes, which was fairly low, and some research, where we found that in one of the main social networks today, Facebook, the average person has 150 friends. Since in this application you share something even more private than your photos, which is your real-time location, we assume that this number will be even lower, since there will be only close friends. Besides, using SOLID guarantees that our users will be people that worry about their own privacy, which will probably work in the same direction.

Status::

Rejected.

Consequences::

SOLID principles are stronger in our application, since there is no kind of central server and the application works even if deployed locally by the user. Besides, we also avoid mutual interference in performance between users and add an extra layer of security: if there are no central servers nor databases, they cannot be attacked and, in case a user had too many friends for the application to handle mantaining an acceptable performance, it would affect only them.

=== Usage of an optimization ring system to obtain friends' locations.

Context:: 

Even if, as explained above, the average user of this app will not have too many friends, just in case we decided to create an optimization system to reduce the number of POD requests we send. The reasoning behind it is that you don't need to constantly request a location that you won't display since it is too far away. E.g: If your friend is in Madrid and you are in Oviedo with a range of 5km, it will take at least 1 hour for your friend to be close enough to be painted in the map. In this mean time we do not need to upload their location as frequently.

Decision::

The friends are divided in 3 different rings according to their distance to the user after the first time the whole list is traversed. From then on, each ring will be assigned a time interval after which it will be updated

Status::

Accepted.

Consequences::

Improvement in performance, which will be greater for users with lots of friends.

=== Use of admin role

Context:: 

The app specification an admin was required. This admin could manage some decisions about the users. 

Decision::

After discussing this issue and considering the implementation of our app, we decided that it was completely useless to have an admin role user. All the controls that users need are provided and each user can only control their current location sharing and the list of friends. An admin here could not do anything special without breaking the main principles of the application.

Status::

Accepted.

Consequences::

A cleaner app with complete authority over user information on each user.

=== Use of a library for notifications

Context:: 

The app needed a notification system which informs the user of when a friend is nearby. This notifications should be shown when a friend of the user enters the ring or the ring's size changes. 

Decision::

Creating our own system would be way too complex and time demanding. Also we would have needed to work a lot with css.

Status::

Accepted.

Consequences::

We found a notification react component that was pretty useful so we did not need to implement our own solution.

